//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Bolum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Bolum()
        {
            this.tbl_Ogretmen = new HashSet<tbl_Ogretmen>();
        }
    
        public byte Bolum_id { get; set; }
        public string Bolum_Adı { get; set; }
        public Nullable<byte> Fakulte_id { get; set; }
    
        public virtual tbl_Fakulte tbl_Fakulte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ogretmen> tbl_Ogretmen { get; set; }
    }
}
