//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OnlineDers
    {
        public int OnlineDers_id { get; set; }
        public Nullable<int> YapılacakDers_id { get; set; }
    
        public virtual tbl_YapılacakDers tbl_YapılacakDers { get; set; }
    }
}
