//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Ogretmen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Ogretmen()
        {
            this.tbl_Danısman = new HashSet<tbl_Danısman>();
            this.tbl_Ders = new HashSet<tbl_Ders>();
            this.tbl_AdminLog = new HashSet<tbl_AdminLog>();
        }
        public int Ogretmen_id { get; set; }
        [Required]
        public string Ogretmen_KullanıcıAdı { get; set; }
        [Required]
        public string Ogretmen_Sifre { get; set; }
        [Required]
        public string Ogretmen_Ad { get; set; }
        [Required]
        public string Ogretmen_Soyad { get; set; }
        [Required]
        public Nullable<bool> Ogretmen_Durum { get; set; }
        [Required]
        public Nullable<byte> Bolum_id { get; set; }
        [Required]
        public string Api_secret { get; set; }
        [Required]
        public string Api_Key { get; set; }
        [Required]
        public string Client { get; set; }
    
        public virtual tbl_Bolum tbl_Bolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Danısman> tbl_Danısman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ders> tbl_Ders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AdminLog> tbl_AdminLog { get; set; }
    }
}
