//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ogretim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Ogretim()
        {
            this.tbl_Ders = new HashSet<tbl_Ders>();
        }
    
        public byte Ogretim_id { get; set; }
        public string Ogretim_Ad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ders> tbl_Ders { get; set; }
    }
}
