//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AlınanDersler
    {
        public int AlınanDers_id { get; set; }
        public Nullable<int> Ogrenci_id { get; set; }
        public Nullable<int> Ders_id { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual tbl_Ders tbl_Ders { get; set; }
        public virtual tbl_Ogrenci tbl_Ogrenci { get; set; }
    }
}
