//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AdminLog
    {
        public int AdminLog_id { get; set; }
        public Nullable<int> Admin_id { get; set; }
        public Nullable<int> İşlem_id { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> YapılacakDers_id { get; set; }
        public Nullable<int> Ogretmen_id { get; set; }
        public Nullable<int> Ogrenci_id { get; set; }
        public Nullable<int> Ders_id { get; set; }
    
        public virtual tbl_Admin tbl_Admin { get; set; }
        public virtual tbl_Ders tbl_Ders { get; set; }
        public virtual tbl_İşlem tbl_İşlem { get; set; }
        public virtual tbl_Ogrenci tbl_Ogrenci { get; set; }
        public virtual tbl_Ogretmen tbl_Ogretmen { get; set; }
        public virtual tbl_YapılacakDers tbl_YapılacakDers { get; set; }
    }
}
