//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Ogrenci()
        {
            this.tbl_AlınanDersler = new HashSet<tbl_AlınanDersler>();
            this.tbl_Danısman = new HashSet<tbl_Danısman>();
            this.tbl_Mesaj = new HashSet<tbl_Mesaj>();
            this.tbl_AdminLog = new HashSet<tbl_AdminLog>();
        }
    
        public int Ogrenci_id { get; set; }
        [Required]
        public string Ogrenci_Tc { get; set; }
        [Required]
        public string Ogrenci_No { get; set; }
        [Required]
        public string Ogrenci_Ad { get; set; }
        [Required]
        public string Ogrenci_Soyad { get; set; }
        public Nullable<bool> Ogrenci_Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AlınanDersler> tbl_AlınanDersler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Danısman> tbl_Danısman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Mesaj> tbl_Mesaj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AdminLog> tbl_AdminLog { get; set; }
    }
}
