//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mesaj
    {
        public int Mesaj_id { get; set; }
        public Nullable<int> Danısman_id { get; set; }
        public string Mesaj { get; set; }
        public string Yanıt { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> Ogrenci_id { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<System.DateTime> Yanıtlanma_Tarihi { get; set; }
    
        public virtual tbl_Danısman tbl_Danısman { get; set; }
        public virtual tbl_Ogrenci tbl_Ogrenci { get; set; }

        public string Y_Mesaj { get; set; }
    }
}
